services:
  rihigo-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rihigo-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ORIGIN=https://rihigo.com
      - API_URL=https://api.rihigo.com
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=https://rihigo.com
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_IMAGES_TOKEN=${CLOUDFLARE_IMAGES_TOKEN}
      - CLOUDFLARE_IMAGES_HASH=${CLOUDFLARE_IMAGES_HASH}
